routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
|--------------------------------------------------------------------------
| Frontend
|--------------------------------------------------------------------------|
*/

// Home
Route::name('home')->get('/', 'Front\PostController@index');

// Contact
Route::resource('contacts', 'Front\ContactController', ['only' => ['create', 'store']]);

// Posts and comments
Route::prefix('posts')->namespace('Front')->group(function () {
    Route::name('posts.display')->get('{slug}', 'PostController@show');
    Route::name('posts.tag')->get('tag/{tag}', 'PostController@tag');
    Route::name('posts.search')->get('', 'PostController@search');
    Route::name('posts.comments.store')->post('{post}/comments', 'CommentController@store');
    Route::name('posts.comments.comments.store')->post('{post}/comments/{comment}/comments', 'CommentController@store');
    Route::name('posts.comments')->get('{post}/comments/{page}', 'CommentController@comments');
});

Route::resource('comments', 'Front\CommentController', [
    'only' => ['update', 'destroy'],
    'names' => ['destroy' => 'front.comments.destroy']
]);

Route::name('category')->get('category/{category}', 'Front\PostController@category');

// Authentification
Auth::routes();


Route::post('/', 'PagesController@postContact');


/*
|--------------------------------------------------------------------------
| Backend
|--------------------------------------------------------------------------|
*/

Route::prefix('admin')->namespace('Back')->group(function () {

    Route::middleware('redac')->group(function () {

        Route::name('admin')->get('/', 'AdminController@index');

        // Posts
        Route::name('posts.seen')->put('posts/seen/{post}', 'PostController@updateSeen')->middleware('can:manage,post');
        Route::name('posts.active')->put('posts/active/{post}/{status?}', 'PostController@updateActive')->middleware('can:manage,post');
        Route::resource('posts', 'PostController');

        // Notifications
        Route::name('notifications.index')->get('notifications/{user}', 'NotificationController@index');
        Route::name('notifications.update')->put('notifications/{notification}', 'NotificationController@update');

        // Medias
        Route::view('medias', 'back.medias')->name('medias.index');

    });

    Route::middleware('admin')->group(function () {

        // Users
        Route::name('users.seen')->put('users/seen/{user}', 'UserController@updateSeen');
        Route::name('users.valid')->put('users/valid/{user}', 'UserController@updateValid');
        Route::resource('users', 'UserController', ['only' => [
            'index', 'edit', 'update', 'destroy'
        ]]);

        // Categories
        Route::resource('categories', 'CategoryController', ['except' => 'show']);

        // Contacts
        Route::name('contacts.seen')->put('contacts/seen/{contact}', 'ContactController@updateSeen');
        Route::resource('contacts', 'ContactController', ['only' => [
            'index', 'destroy'
        ]]);

        // Comments
        Route::name('comments.seen')->put('comments/seen/{comment}', 'CommentController@updateSeen');
        Route::resource('comments', 'CommentController', ['only' => [
            'index', 'destroy'
        ]]);

        // Settings
        Route::name('settings.edit')->get('settings', 'AdminController@settingsEdit');
        Route::name('settings.update')->put('settings', 'AdminController@settingsUpdate');

    });



});

app/Models/Comment.php
<?php

namespace App\Models;

use App\Events\ModelCreated;
use Baum\Node;

class Comment extends Node
{
    use IngoingTrait;

    /**
     * The event map for the model.
     *
     * @var array
     */
    protected $dispatchesEvents = [
        'created' => ModelCreated::class,
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['body', 'post_id', 'user_id', 'parent_id'];

    /**
     * One to Many relation
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * One to Many relation
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function post()
    {
        return $this->belongsTo (Post::class);
    }
}

app/Http/Controllers/Back/CommentController.php
<?php

namespace App\Http\Controllers\Back;

use App\ {
    Models\Comment,
    Repositories\CommentRepository,
    Http\Controllers\Controller
};

class CommentController extends Controller
{
    use Indexable;

    /**
     * Create a new CommentController instance.
     *
     * @param  \App\Repositories\CommentRepository $repository
     */
    public function __construct(CommentRepository $repository)
    {
        $this->repository = $repository;

        $this->table = 'comments';
    }

    /**
     * Update "new" field for comment.
     *
     * @param  \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function updateSeen(Comment $comment)
    {
        $comment->ingoing->delete ();

        return response ()->json ();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Comment $comment
     * @return \Illuminate\Http\Response
     */
    public function destroy(Comment $comment)
    {
        $comment->delete ();

        return response ()->json ();
    }
}

app/Http/Controllers/Front/CommentController.php
<?php

namespace App\Http\Controllers\Front;

use App\ {
    Http\Controllers\Controller,
    Http\Requests\CommentRequest,
    Repositories\CommentRepository,
    Notifications\Commented,
    Models\Post,
    Models\Comment
};

class CommentController extends Controller
{
    /**
     * Create a new CommentController instance.
     *
     * @param  \App\Repositories\CommentRepository $commentRepository
     */
    public function __construct(CommentRepository $commentRepository)
    {
        $this->commentRepository = $commentRepository;

        $this->middleware('auth')->only('store', 'destroy', 'update');
    }

    /**
     * Store a newly created comment in storage.
     *
     * @param  \App\http\requests\CommentRequest $request
     * @param  \App\Models\Post  $post
     * @param  integer $comment_id
     * @return \Illuminate\Http\Response
     */
    public function store(CommentRequest $request, Post $post, $comment_id = null)
    {
        Comment::create ([
            'body' => $request->input('message' . $comment_id),
            'post_id' => $post->id,
            'user_id' => $request->user()->id,
            'parent_id' => $comment_id,
        ]);

        $post->user->notify(new Commented($post, $request->user()->id));

        if (!$request->user()->valid) {
            $request->session()->flash('warning', __('Thanks for your comment. It will appear when an administrator has validated it.<br>Once you are validated your other comments immediately appear.'));
        }

        if($request->ajax()) {
            return response()->json();
        }

        return back();
    }

    /**
     * Update the specified comment in storage.
     *
     * @param  \App\Http\requests\CommentRequest $request
     * @param  \App\Models\Comment  $comment
     * @return array
     */
    public function update(CommentRequest $request, Comment $comment)
    {
        $this->authorize('manage', $comment);

        $message = $request->input('message' . $comment->id);
        $comment->body = $message;
        $comment->save();

        return ['id' => $comment->id, 'message' => $message];
    }

    /**
     * Remove the specified comment from storage.
     * @param Comment $comment
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Comment $comment)
    {
        $this->authorize('manage', $comment);

        $comment->delete();

        return back();
    }

    /**
     * Get the next comments for the specified post.
     *
     * @param  \App\Models\Post  $post
     * @param  integer $page
     * @return array
     */
    public function comments(Post $post, $page)
    {
        $comments = $this->commentRepository->getNextComments($post, $page);
        $count = $post->parentComments()->count();
        $level = 0;

        return [
            'html' => view('front/comments/comments', compact('post', 'comments', 'level'))->render(),
            'href' => $count <= config('app.numberParentComments') * ++$page ?
                'none'
                : route('posts.comments', [$post->id, $page]),
        ];
    }
}

app/Http/Controllers/Front/ContactController.php
<?php

namespace App\Http\Controllers\Front;

use App\ {
    Http\Controllers\Controller,
    Http\Requests\ContactRequest,
    Models\Contact
};

class ContactController extends Controller
{
    /**
     * Create a new ContactController instance.
     *
     */
    public function __construct()
    {
        $this->middleware('guest');
    }

    /**
     * Show the form for creating a new contact.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('front.contact');
    }

    /**
     * Store a newly created contact in storage.
     *
     * @param  ContactRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(ContactRequest $request)
    {
        Contact::create ($request->all ());

        return back ()->with ('ok', __('Your message has been recorded, we will respond as soon as possible.'));
    }
}

app/Http/Controllers/Front/PostController.php
<?php

namespace App\Http\Controllers\Front;

use App\ {
    Http\Controllers\Controller,
    Http\Requests\SearchRequest,
    Repositories\PostRepository,
    Models\Tag,
    Models\Category
};
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * The PostRepository instance.
     *
     * @var \App\Repositories\PostRepository
     */
    protected $postRepository;

    /**
     * The pagination number.
     *
     * @var int
     */
    protected $nbrPages;

    /**
     * Create a new PostController instance.
     *
     * @param  \App\Repositories\PostRepository $postRepository
     * @return void
    */
    public function __construct(PostRepository $postRepository)
    {
        $this->postRepository = $postRepository;
        $this->nbrPages = config('app.nbrPages.front.posts');
    }

    /**
     * Display a listing of the posts.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = $this->postRepository->getActiveOrderByDate($this->nbrPages);
        $chunk = $posts->take(3);
        $chunk->all();

        return view('front.index', compact('chunk'));
    }

    /**
     * Display a listing of the posts for the specified category.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function category(Category $category)
    {
        $posts = $this->postRepository->getActiveOrderByDateForCategory($this->nbrPages, $category->slug);
        $info = __('Posts for category: ') . '<strong>' . $category->title . '</strong>';

        return view('front.index', compact('posts', 'info'));
    }

    /**
     * Display the specified post by slug.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  string $slug
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, $slug)
    {
        $user = $request->user();

        return view('front.post', array_merge($this->postRepository->getPostBySlug($slug), compact('user')));
    }

    /**
     * Get posts for specified tag
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function tag(Tag $tag)
    {
        $posts = $this->postRepository->getActiveOrderByDateForTag($this->nbrPages, $tag->id);
        $info = __('Posts found with tag ') . '<strong>' . $tag->tag . '</strong>';

        return view('front.index', compact('posts', 'info'));
    }

    /**
     * Get posts with search
     *
     * @param  \App\Http\Requests\SearchRequest $request
     * @return \Illuminate\Http\Response
     */
    public function search(SearchRequest $request)
    {
        $search = $request->search;
        $posts = $this->postRepository->search($this->nbrPages, $search)->appends(compact('search'));
        $info = __('Posts found with search: ') . '<strong>' . $search . '</strong>';

        return view('front.index', compact('posts', 'info'));
    }
}

resources/views/front/comments/comments-base.blade.php
<li>
    <div class="avatar">
        <img width="50" height="50" class="avatar" src="{{ Gravatar::get($comment->user->email) }}" alt="">
    </div>

    <div class="comment-content">

        <div class="comment-info">
            <cite>{{ $comment->user->name }}</cite>

            @if(Auth::check() && Auth::user()->name == $comment->user->name)
                <a href="#" class="deletecomment"><span class="fa fa-fw fa-trash fa-lg  pull-right" title="@lang('Delete comment')"></span></a>
                <form action="{{ route('front.comments.destroy', [$comment->id]) }}" method="POST" class="hide">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                </form>
                <a id="comment-edit{!! $comment->id !!}" href="#" class="editcomment"><span class="fa fa-fw fa-pencil fa-lg pull-right" title="@lang('Edit comment')"></span></a>
            @endif

            <div class="comment-meta">
                <time class="comment-time" datetime="{{ $comment->created_at }}">{{ ucfirst (utf8_encode ($comment->created_at->formatLocalized('%A %d %B %Y'))) }}</time>
                @if(Auth::check() && $level < config('app.commentsNestedLevel'))
                    <span class="sep">/</span><a id="reply-create{!! $comment->id !!}" class="reply" href="#">@lang('Reply')</a>
                    <form id="reply-form{{ $comment->id }}" method="post" action="{{ route('posts.comments.comments.store', [$post->id, $comment->id]) }}" class="reply-form hide">
                        {{ csrf_field() }}
                        <div class="form-field">
                            <strong class="red"></strong>
                            <textarea name="message{{ $comment->id }}" id="message{{ $comment->id }}" placeholder="@lang('Your Reply')" class="full-width" required></textarea>
                        </div>
                        <button id="reply-escape{{ $comment->id }}" class="btnescapereply">@lang('Escape')</button>
                        <button type="submit" class="submit button-primary">@lang('Submit')</button>
                    </form>
                @endif
            </div>
        </div>

        <div class="comment-text">
            <p id="comment-body{{ $comment->id }}">{{ $comment->body }}</p>

            @if(Auth::check() && Auth::user()->name == $comment->user->name)
                <form id="comment-form{{ $comment->id }}" method="post" action="{{ route('comments.update', [$comment->id]) }}" class="comment-form hide">
                    {{ csrf_field() }}
                    <div class="form-field">
                        <strong class="red"></strong>
                        <textarea title="message" name="message{{ $comment->id }}" id="message{{ $comment->id }}" class="full-width" required></textarea>
                    </div>
                    <button id="comment-escape{{ $comment->id }}" class="btnescape">@lang('Escape')</button>
                    <button type="submit" class="submit button-primary">@lang('Submit')</button>
                </form>
            @endif

        </div>

        @unless ($comment->isLeaf())
            @php
                $level++;
            @endphp
            <ul class="children">
                @include('front/comments/comments', ['comments' => $comment->getImmediateDescendants()])
            </ul>
        @endunless

    </div>
</li>

resources/views/front/comments/comments.blade.php
@foreach($comments as $comment)
    @include('front/comments/comments-base')
@endforeach